name: "自动打包发布"
on: 
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: 导出游戏
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 修复虚拟机的写入权限
        run: chmod -R 777 .

      # ==========================
      # 【核心新增】：给 Linux 服务器加装图标注入套件
      # ==========================
      - name: 准备 Windows 图标注入环境 (Wine & rcedit)
        run: |
          sudo apt-get update
          sudo apt-get install -y wine64
          wget https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe

      - name: Godot 导出
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          use_preset_export_path: true
          export_debug: false
          verbose: true
          # ==========================
          # 【核心新增】：把 Wine 和 rcedit 的路径传给 Godot 引擎
          # ==========================
          wine_path: /usr/bin/wine64
          custom_editor_settings: export/windows/rcedit=./rcedit-x64.exe

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: Vector-Combat-Windows
          path: build/